# -*- coding: utf-8 -*-
"""Car price predictor (Muthu Sriram K).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyObGmWIFBAQkbQIX9hlvYfY_uU8vWkc
"""

"""
generate_dataset.py
--------------------
Generates a synthetic but realistic car dataset covering Petrol, Diesel,
and EV cars with price + performance specs.

If you have a REAL dataset (e.g. from Kaggle "Car Price Prediction" or
"Vehicle Dataset"), just replace this step — load your CSV instead and
make sure it has similar column names (see bottom of this file).
"""

import numpy as np
import pandas as pd

np.random.seed(42)

N_PER_TYPE = 600  # number of synthetic cars per fuel type

brands_budget = ["Maruti Suzuki", "Tata", "Hyundai", "Renault", "Datsun"]
brands_mid = ["Honda", "Toyota", "Hyundai", "Kia", "Skoda", "Volkswagen"]
brands_premium = ["BMW", "Audi", "Mercedes-Benz", "Volvo", "Jaguar"]
ev_brands = ["Tata", "MG", "Hyundai", "BYD", "Mahindra", "Tesla"]

rows = []

def rand_choice_weighted(options, weights):
    return np.random.choice(options, p=np.array(weights) / sum(weights))

# ---------------- PETROL ----------------
for _ in range(N_PER_TYPE):
    segment = rand_choice_weighted(["budget", "mid", "premium"], [0.5, 0.35, 0.15])
    if segment == "budget":
        brand = np.random.choice(brands_budget)
        engine_cc = np.random.randint(800, 1300)
        power_bhp = np.random.randint(55, 95)
        base_price = np.random.uniform(4.5, 9.0)       # lakhs INR
    elif segment == "mid":
        brand = np.random.choice(brands_mid)
        engine_cc = np.random.randint(1300, 2000)
        power_bhp = np.random.randint(95, 160)
        base_price = np.random.uniform(9.0, 18.0)
    else:
        brand = np.random.choice(brands_premium)
        engine_cc = np.random.randint(1800, 3000)
        power_bhp = np.random.randint(160, 280)
        base_price = np.random.uniform(35.0, 80.0)

    year = np.random.randint(2015, 2025)
    mileage_kmpl = round(np.random.uniform(12, 23) - (power_bhp / 100), 1)
    mileage_kmpl = max(8, mileage_kmpl)
    seats = np.random.choice([5, 5, 5, 7])
    maintenance_cost_per_year = round(np.random.uniform(8000, 25000), -2)
    price_lakhs = round(base_price * (1 + (year - 2015) * 0.015) * (1 + power_bhp / 1000), 2)

    rows.append([brand, "Petrol", year, engine_cc, power_bhp, mileage_kmpl,
                 None, None, seats, maintenance_cost_per_year, price_lakhs])

# ---------------- DIESEL ----------------
for _ in range(N_PER_TYPE):
    segment = rand_choice_weighted(["budget", "mid", "premium"], [0.35, 0.45, 0.20])
    if segment == "budget":
        brand = np.random.choice(brands_budget)
        engine_cc = np.random.randint(1200, 1500)
        power_bhp = np.random.randint(70, 100)
        base_price = np.random.uniform(6.5, 11.0)
    elif segment == "mid":
        brand = np.random.choice(brands_mid)
        engine_cc = np.random.randint(1500, 2200)
        power_bhp = np.random.randint(100, 180)
        base_price = np.random.uniform(11.0, 22.0)
    else:
        brand = np.random.choice(brands_premium)
        engine_cc = np.random.randint(2000, 3000)
        power_bhp = np.random.randint(180, 300)
        base_price = np.random.uniform(40.0, 90.0)

    year = np.random.randint(2015, 2025)
    mileage_kmpl = round(np.random.uniform(16, 28) - (power_bhp / 120), 1)
    mileage_kmpl = max(10, mileage_kmpl)
    seats = np.random.choice([5, 5, 7, 7])
    maintenance_cost_per_year = round(np.random.uniform(10000, 30000), -2)
    price_lakhs = round(base_price * (1 + (year - 2015) * 0.015) * (1 + power_bhp / 1000), 2)

    rows.append([brand, "Diesel", year, engine_cc, power_bhp, mileage_kmpl,
                 None, None, seats, maintenance_cost_per_year, price_lakhs])

# ---------------- EV ----------------
for _ in range(N_PER_TYPE):
    segment = rand_choice_weighted(["budget", "mid", "premium"], [0.30, 0.45, 0.25])
    brand = np.random.choice(ev_brands)
    if segment == "budget":
        battery_kwh = np.random.uniform(20, 35)
        power_bhp = np.random.randint(60, 100)
        base_price = np.random.uniform(8.0, 14.0)
    elif segment == "mid":
        battery_kwh = np.random.uniform(35, 55)
        power_bhp = np.random.randint(100, 180)
        base_price = np.random.uniform(14.0, 28.0)
    else:
        battery_kwh = np.random.uniform(55, 100)
        power_bhp = np.random.randint(180, 500)
        base_price = np.random.uniform(45.0, 120.0)

    year = np.random.randint(2018, 2025)
    range_km = round(battery_kwh * np.random.uniform(5.5, 7.5), 0)  # rough Wh/km efficiency
    seats = np.random.choice([5, 5, 7])
    # EVs cost far less per year to "fuel" + service
    maintenance_cost_per_year = round(np.random.uniform(4000, 12000), -2)
    price_lakhs = round(base_price * (1 + (year - 2018) * 0.02) * (1 + power_bhp / 1500), 2)

    rows.append([brand, "EV", year, None, power_bhp, None,
                 round(battery_kwh, 1), range_km, seats, maintenance_cost_per_year, price_lakhs])

df = pd.DataFrame(rows, columns=[
    "brand", "fuel_type", "year", "engine_cc", "power_bhp", "mileage_kmpl",
    "battery_kwh", "range_km", "seats", "maintenance_cost_per_year", "price_lakhs"
])

df.to_csv("car_dataset.csv", index=False)
print("Dataset created:", df.shape)
print(df.groupby("fuel_type")["price_lakhs"].describe())

"""
train_model.py
---------------
Trains a machine learning model to PREDICT car price (in lakhs INR)
from specs, for Petrol, Diesel, and EV cars.

Model: RandomForestRegressor (handles non-linear relationships + mixed
categorical/numeric features well, and works great on small/medium data).
"""

import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# 1. Load data ---------------------------------------------------------
df = pd.read_csv("car_dataset.csv")

TARGET = "price_lakhs"

categorical_features = ["brand", "fuel_type"]
numeric_features = ["year", "engine_cc", "power_bhp", "mileage_kmpl",
                     "battery_kwh", "range_km", "seats", "maintenance_cost_per_year"]

X = df[categorical_features + numeric_features]
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Preprocessing -------------------------------------------------------
# Numeric: fill missing (EVs have no engine_cc/mileage, petrol/diesel have no battery/range)
#          then scale.
numeric_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

# 3. Full model pipeline ----------------------------------------------
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
        n_estimators=300, max_depth=12, random_state=42, n_jobs=-1
    ))
])

# 4. Train ---------------------------------------------------------------
model.fit(X_train, y_train)

# 5. Evaluate --------------------------------------------------------
preds = model.predict(X_test)
mae = mean_absolute_error(y_test, preds)
r2 = r2_score(y_test, preds)

print(f"Model Performance on Test Set:")
print(f"  MAE  (avg error) : ₹{mae:.2f} lakhs")
print(f"  R²   (fit score) : {r2:.3f}  (closer to 1.0 = better)")

# 6. Save model + dataset for reuse --------------------------------------
joblib.dump(model, "car_price_model.pkl")
print("\nModel saved to car_price_model.pkl")

"""
recommend_car.py
------------------
Main user-facing script.

What it does:
1. Loads the trained ML price-prediction model + dataset.
2. Asks for the family's ANNUAL SALARY (income).
3. Works out a sensible car budget from that salary using the
   standard personal-finance rule of thumb:
        Affordable car price  =  40% to 50% of ANNUAL salary
   (You can change AFFORDABILITY_RATIO below if you want to be
   more conservative or more aggressive.)
4. Filters cars within budget, scores each one on PERFORMANCE
   (power, efficiency/range, running cost) and VALUE (performance
   per rupee).
5. Picks the single best Petrol, best Diesel, and best EV pick,
   then declares an overall WINNER for the family.

Run:  python3 recommend_car.py
"""

import pandas as pd
import numpy as np
import joblib

# ----------------------- CONFIG --------------------------------------
AFFORDABILITY_RATIO = 0.45   # max car price = 45% of annual salary (lakhs)
LAKH = 100_000                # 1 lakh = 100,000 INR

# ----------------------- LOAD ASSETS ----------------------------------
df = pd.read_csv("car_dataset.csv")
model = joblib.load("car_price_model.pkl")


def predict_price(row: dict) -> float:
    """Use the trained ML model to predict price (lakhs) for a single car spec."""
    input_df = pd.DataFrame([row])
    return float(model.predict(input_df)[0])


def performance_score(row) -> float:
    """
    A 0-100 performance score blending power, efficiency, and running cost.
    Different formula per fuel type since EV/petrol/diesel specs differ.
    """
    power = row["power_bhp"]
    maint = row["maintenance_cost_per_year"]

    if row["fuel_type"] == "EV":
        efficiency_term = (row["range_km"] / 10)         # range matters a lot for EVs
    else:
        efficiency_term = (row["mileage_kmpl"] * 4)       # mileage matters for ICE cars

    running_cost_penalty = maint / 1000                   # higher maintenance = worse

    raw_score = (power * 0.5) + efficiency_term - running_cost_penalty
    return raw_score


def normalize(series):
    return (series - series.min()) / (series.max() - series.min() + 1e-9) * 100


def get_recommendations(annual_salary_lakhs: float, family_size: int = 4):
    budget = annual_salary_lakhs * AFFORDABILITY_RATIO

    candidates = df[df["price_lakhs"] <= budget].copy()
    candidates = candidates[candidates["seats"] >= min(family_size, 5)]  # basic seating need

    if candidates.empty:
        return None, budget, None

    candidates["perf_raw"] = candidates.apply(performance_score, axis=1)
    candidates["perf_score"] = normalize(candidates["perf_raw"])
    candidates["value_score"] = normalize(candidates["perf_score"] / (candidates["price_lakhs"] + 1))
    # Final score: blend of performance + value-for-money
    candidates["final_score"] = candidates["perf_score"] * 0.6 + candidates["value_score"] * 0.4

    best_per_fuel = (
        candidates.sort_values("final_score", ascending=False)
        .groupby("fuel_type")
        .first()
        .reset_index()
    )

    overall_best = candidates.sort_values("final_score", ascending=False).iloc[0]

    return best_per_fuel, budget, overall_best


def print_report(annual_salary_lakhs, family_size=4):
    print("=" * 70)
    print(f" FAMILY CAR RECOMMENDATION REPORT")
    print("=" * 70)
    print(f"Annual Family Salary : ₹{annual_salary_lakhs:.2f} lakhs/year")
    print(f"Family Size          : {family_size}")

    best_per_fuel, budget, overall_best = get_recommendations(annual_salary_lakhs, family_size)

    print(f"Recommended Max Car Budget (~{int(AFFORDABILITY_RATIO*100)}% of salary): "
          f"₹{budget:.2f} lakhs")
    print("-" * 70)

    if best_per_fuel is None:
        print("No cars found within this budget for the given family size.")
        print("Tip: increase savings, consider used cars, or a smaller segment.")
        return

    print("\nBEST PICK PER FUEL TYPE:\n")
    for _, row in best_per_fuel.iterrows():
        print(f"  [{row['fuel_type']}] {row['brand']}  |  Year: {int(row['year'])}")
        print(f"     Price          : ₹{row['price_lakhs']:.2f} lakhs")
        print(f"     Power          : {row['power_bhp']} bhp")
        if row["fuel_type"] == "EV":
            print(f"     Battery/Range  : {row['battery_kwh']} kWh / {row['range_km']} km")
        else:
            print(f"     Engine/Mileage : {row['engine_cc']} cc / {row['mileage_kmpl']} km-pl")
        print(f"     Annual upkeep  : ₹{row['maintenance_cost_per_year']:.0f}")
        print(f"     Performance Score (0-100): {row['perf_score']:.1f}")
        print()

    print("-" * 70)
    print(f"OVERALL BEST CHOICE FOR YOUR FAMILY:")
    print(f"   >>> {overall_best['fuel_type']} | {overall_best['brand']} "
          f"({int(overall_best['year'])}) — ₹{overall_best['price_lakhs']:.2f} lakhs <<<")
    print(f"   Why: Best balance of performance, running cost, and affordability")
    print(f"   for a ₹{annual_salary_lakhs:.1f} lakh/year household.")
    print("=" * 70)


# ----------------------- INTERACTIVE MODE -----------------------------
if __name__ == "__main__":
    try:
        salary_input = input("Enter family ANNUAL salary (in ₹ lakhs, e.g. 12 for 12,00,000): ")
        annual_salary_lakhs = float(salary_input)
        family_size_input = input("Enter family size (default 4): ") or "4"
        family_size = int(family_size_input)
    except ValueError:
        print("Invalid input, using example values: salary=12 lakhs, family size=4")
        annual_salary_lakhs, family_size = 12, 4

    print_report(annual_salary_lakhs, family_size)